- name: install backup script
  template:
    src: "backup.sh.j2"
    dest: "/opt/minecraft/backup.sh"
    owner: minecraft
    group: minecraft
    mode: '0755'
  become: yes

- name: set backup cron
  cron:
    name: "backup world"
    user: minecraft
    minute: 0
    hour: "*/4"
    job: /opt/minecraft/backup.sh
  become: yes

- name: install recovery script
  template:
    src: "recovery.sh.j2"
    dest: "/opt/minecraft/recovery.sh"
    owner: minecraft
    group: minecraft
    mode: '0755'
  become: yes