- name: add minecraft user
  user: name=minecraft password={{minecraft_user_pass}} state=present
  become: yes

- name: add sudoers
  lineinfile: "dest=/etc/sudoers backup=yes state=present regexp='^minecraft' line='minecraft ALL=(ALL) NOPASSWD: ALL'"
  become: yes

- name: make minecraft directory
  file: path=/opt/minecraft state=directory owner=minecraft group=minecraft mode=0755
  become: yes

- name: download minecraft forge server jar
  get_url:
    url: https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2705/forge-1.12.2-14.23.4.2705-installer.jar
    dest: /opt/minecraft
  become: yes

- name: install forge server
  shell: /usr/bin/java -jar forge-1.12.2-14.23.4.2705-installer.jar --installServer
  args:
    chdir: /opt/minecraft
  become: yes

- name: create symbolic link
  file: src=/opt/minecraft/forge-1.12.2-14.23.4.2705-universal.jar dest=/opt/minecraft/minecraft_server.jar state=link owner=minecraft group=minecraft
  become: yes

- name: agree to EULA
  copy:
    src: eula.txt
    dest: "/opt/minecraft/eula.txt"
    mode: '0644'
    owner: "minecraft"
    group: "minecraft"
  become: yes

- name: make mods directory
  file: path=/opt/minecraft/mods state=directory owner=minecraft group=minecraft mode=0755
  become: yes

- name: get mods
  get_url:
    url: "{{ item }}"
    dest: /opt/minecraft/mods
    mode: '0644'
    owner: "minecraft"
    group: "minecraft"
  with_items:
    - "{{ minecraft_mods }}"
  become: yes

- name: create mods directory
  file: path=/home/minecraft/files/{{ item }} state=directory owner=minecraft group=minecraft mode=0755
  with_items:
    - mods
    - forge
  become: yes

- name: copy mods file
  shell: cp /opt/minecraft/mods/*.jar /home/minecraft/files/mods/
  become: yes

- name: copy forge file
  shell: cp /opt/minecraft/forge*installer.jar /home/minecraft/files/mods/
  become: yes

- name: create tar ball
  archive:
    path: /home/minecraft/files
    format: gz
    dest: /home/minecraft/files.tar.gz
  become: yes

- name: install units
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - minecraft.service
  notify:
    - enable service
    - restart Minecraft
  register: systemd_service_config
  become: yes

- name: reload systemd
  command: systemctl daemon-reload
  become: true
  when: systemd_service_config.changed


